version: 0

debug: False

data:
  root_folder: "/home/psrahul/MasterThesis/datasets/CUB_200_2011/v2/CUB_200_2011/"
  train_folder: "train/images"
  val_folder: "val/images"
  test_folder: "test/images"
  train_batch_size: 16
  val_batch_size: 16
  test_batch_size: 16

model:
  encoder_name: ViTB16Model
  use_pretrained: True
  freeze_params: False


logging:
  exp_name: "ViT_1e-5"
  checkpoint_dir: "checkpoints/ViTB16Model"
  max_epochs: 200
  lr: 1e-5

