version: 0

dataset_class_debug: False

data:
  train_data_root: "/home/psrahul/MasterThesis/datasets/PASCAL_2012_MINI/base_classes/train/coco/"
  val_data_root: "/home/psrahul/MasterThesis/datasets/PASCAL_2012_MINI/base_classes/val/coco/"
  train_aug: True
  train_batch_size: 32
  val_batch_size: 32
trainer:
  num_epochs: 100

heatmap:
  output_dimension: 96
  radius_scaling: 10
  fix_radius: True
  fix_radius_value: 5
max_objects_per_image: 5
model:
  encoder:
    encoder_name: ResNet18Model
    use_pretrained: True
    freeze_params: False
  decoder:
    input_num_filter: 512
    num_layers: 3
    output_num_filter: [ 256,128,64 ]
  heatmap_head:
    input_num_filter: 64
    output_num_filter: [ 64,1 ]
    kernel_size: [ 3,1 ]

  offset_head:
    input_num_filter: 64
    output_num_filter: [ 64,2 ]
    kernel_size: [ 3,1 ]
  bbox_head:
    input_num_filter: 64
    output_num_filter: [ 64,2 ]
    kernel_size: [ 3,1 ]

logging:
  exp_name: "ResNet18"
  checkpoint_dir: "checkpoints/smoothed_l1"
  log_interval: 20
