version: 0

debug: False

data:
  train_data_root: "/home/psrahul/MasterThesis/datasets/PASCAL_2012_MINI/base_classes/train/coco/"
  val_data_root: "/home/psrahul/MasterThesis/datasets/PASCAL_2012_MINI/base_classes/val/coco/"
  train_aug: True
heatmap:
  output_dimension: 96
  radius_scaling: 5
max_objects_per_image: 25
model:
  encoder:
    encoder_name: ResNet18Model
    use_pretrained: True
    freeze_params: False
  decoder:
    input_num_filter: 512
    num_layers: 3
    output_num_filter: [ 256,256,256 ]
  heatmap_head:
    input_num_filter: 256
    output_num_filter: [ 64,20 ]
    kernel_size: [ 3,1 ]

  offset_head:
    input_num_filter: 256
    output_num_filter: [ 64,2 ]
    kernel_size: [ 3,1 ]
  bbox_head:
    input_num_filter: 256
    output_num_filter: [ 64,2 ]
    kernel_size: [ 3,1 ]

logging:
  exp_name: "ViT_1e-5"
  checkpoint_dir: "checkpoints/test"
  max_epochs: 200
  lr: 1e-5

