data:
  root: "/home/psrahul/MasterThesis/datasets/PASCAL_2012_MINI/base_classes/val/coco/"
prediction_path: "/home/psrahul/MasterThesis/repo/Phase3/CLIPandDetect/Results/EfficientNetB2Model/26082022_0322/bbox_predictions_with_no_scaling.npy"
post_processing:
  score_threshold: 0.8
logging:
  checkpoint_dir: "outputs/metrics/EfficientNetB2Model"
