data:
  root: "/home/psrahul/MasterThesis/datasets/PASCAL_2012_MINI/base_classes/val/coco/"
prediction_path: "/home/psrahul/MasterThesis/repo/Phase3/CLIPandDetect/outputs/inference/EfficientNetB2Model/01092022_1010/bbox_predictions.npy"
post_processing:
  nms_iou_threshold: 0.5
  score_threshold: 0.3
logging:
  checkpoint_dir: "outputs/metrics/EfficientNetB2Model"
